import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ShopProvider } from "@/context/ShopContext";
import { ToastProvider } from "@/context/ToastContext";
import StoreProvider from "@/store/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="font-oxanium min-h-full flex flex-col">
        <StoreProvider>
          <ToastProvider>
            <ShopProvider>{children}</ShopProvider>
          </ToastProvider>
        </StoreProvider>
      </body>
    </html>
  );
}